### PR TITLE
Fixed Plural Formatting For Newer Babel Versions

### PR DESCRIPTION
**Pull request by TheKruspe**

### CODE REVIEW

**Comment by macnewbold** [comment]
Thanks for this! We've been running into the same error lately and were looking into a fix. It's always nice when someone else has already made the pull request you were about to write!

**Comment by imacat** [comment]
Thanks.  It works.  I hope this can be merged into the main branch and a new release will be out soon. ^_^

**Comment by Zbysekz** [comment]
Hello, would be nice to merge this, it fixes the problem

**Comment by julienbordet** [comment]
Had the same problem, was on the verge of fixing it and saw @TheKruspe did the job. Thanks to him for that.
@emdemir , could you please merge it ?

**Comment by BornSupercharged** [comment]
No movement on getting this fixed merged in for this long, come on @emdemir please?

**Comment by emdemir** [comment]
Sorry for not responding for so long. I wrote this project a few jobs ago and never had a use for it afterwards. I'll probably end up rewriting it since embedding the JS file doesn't make much sense. I'm not even sure if it works on the latest Flask version.

**Comment by BornSupercharged** [comment]
@emdemir if you could approve the PR and release tag 1.0.3 that would let everyone just use Flask-Babel-Js==1.0.3

Unless I'm going crazy and 1.0.1 was the latest; in which case just release it as 1.0.2

Even if you're going to rewrite it. Please consider approving and making a new tag for this fix, it's been verified by many different people over the past 2 years and it's literally just one line of code. 

Thank you!

**Comment by emdemir** [comment]
> FWIW: Flask-Babe-JS is still working with Flask 3.1.0 as of today.

That's impressive ^^; I'll take a look at this after New Year's. Allow me two more days please.

**Comment by emdemir** [comment]
Actually, looking at the issue, this seems good to merge away. I'll release a new version as soon as I locate my PyPI credentials...

**Pull request merged**
